### ISSUE TITLE
Some fixes

### ISSUE THREAD

**Issue by junegunn** [mhinz/vim-halo#4]
Hi, nice plugin. I had to change the code a bit to make it work well with [my plugin](https://github.com/junegunn/vim-slash). 

I'm not opening a pull request here as you already seem to be have fixed the major issue (#2) in another branch in a very similar way. But you might want to take a look at the other commits.

https://github.com/junegunn/vim-halo/commits/master

Thanks.

**Comment by mhinz** [comment]
Hi, slash is neat as well!

I cherry-picked your "return empty string" and "fix shape" commits, but couldn't merge the partials one yet, for the reasons mentioned in #2.

But, as far as I can tell, partials support in Neovim isn't far away, and if it lands, I'll immediately fix that pesty bug.
