### ISSUE TITLE
fast window switching triggers E803: ID not found

### ISSUE THREAD

**Issue by sunaku** [mhinz/vim-halo#6]
Hello,

I have configured this plugin to activate after window switching, as follows:

```vim
autocmd WinEnter * call halo#run()
```

However, when I switch _quickly_ between Vim split windows or enter/leave Vim to visit other tmux panes, I encounter errors like the following (only differing in the ID number reported in the error message):

```vim
line    2:
E803: ID not found: 286
Error detected while processing function <SNR>306_tick[3]..<SNR>306_clear:
```

I suppose that one way to work around this problem is to suppress the errors altogether with `:silent!`:

```vim
autocmd WinEnter * silent! call halo#run()
```

But I was wondering if you had a cleaner way to solve this problem than just sweeping it under the rug. :innocent:

Thanks for your consideration.

**Comment by mhinz** [comment]
Ah, I can reproduce it. Will look into it!

**Comment by mhinz** [comment]
Does it work now?

**Comment by sunaku** [comment]
Looks good now, thanks! :+1:
