### ISSUE TITLE
restoring a session triggers E803: ID not found

### ISSUE THREAD

**Issue by sunaku** [mhinz/vim-halo#7]
Hello,

I'm using this plugin along with [obsession.vim](https://github.com/tpope/vim-obsession) and upon restoring a session, I get these errors:

```vim
Error detected while processing function <SNR>330_tick[3]..<SNR>330_clear:
line    2:
E803: ID not found: 47
Error detected while processing function halo#reset[2]..<SNR>330_reset[2]..<SNR>330_clear:
line    2:
E803: ID not found: 47
```

Thanks for your consideration.

**Comment by mhinz** [comment]
- Could you paste your config for obsession (or tell me how you use it)?
- Are you still running halo on `WinEnter`?

**Comment by sunaku** [comment]
Found the problem: the errors occur when [using my custom session loader](https://github.com/sunaku/.vim/blob/master/after/plugin/session.vim) but not when running `vim -S`.

Sorry for the noise.
